import Link from 'next/link';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Chính sách quyền riêng tư | Privacy Policy - MayDo CRM',
  description: 'Chính sách quyền riêng tư và bảo mật thông tin người dùng của MayDo CRM.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-6">
          <Link
            href="/login"
            className="inline-flex items-center gap-2 text-sm text-indigo-400 hover:text-indigo-300 font-medium transition-colors"
          >
            <ArrowLeft size={16} /> Quay lại trang Đăng nhập
          </Link>
          <div className="flex items-center gap-2 text-indigo-400 bg-indigo-500/10 px-3 py-1.5 rounded-full text-xs font-semibold border border-indigo-500/20">
            <ShieldCheck size={16} /> Official Privacy Policy
          </div>
        </div>

        {/* Article Body */}
        <div className="bg-slate-900/80 backdrop-blur-xl border border-slate-800/80 rounded-2xl shadow-2xl p-6 sm:p-10 space-y-6 text-slate-300 text-sm leading-relaxed prose prose-invert max-w-none">
          <h1 className="text-3xl font-bold text-white tracking-tight">Privacy Policy</h1>
          <p className="text-xs text-slate-400">Last updated: July 27, 2026</p>

          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>

          <p>
            We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).
          </p>

          <h2 className="text-xl font-bold text-white pt-4 border-t border-slate-800">Interpretation and Definitions</h2>
          
          <h3 className="text-lg font-semibold text-slate-100">Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-lg font-semibold text-slate-100">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 space-y-2 text-slate-300">
            <li><strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to web quan ly marketing noi bo caykimmaydo.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li>
            <li><strong>Country/State</strong> refers to: Vietnam.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
            <li><strong>User</strong> means any individual who accesses or uses the Service.</li>
            <li><strong>Website</strong> refers to web quan ly marketing noi bo caykimmaydo, accessible from <a href="https://mktmaydo.netlify.app/" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">https://mktmaydo.netlify.app/</a>.</li>
            <li><strong>You</strong> means the individual accessing or using the Service.</li>
          </ul>

          <h2 className="text-xl font-bold text-white pt-4 border-t border-slate-800">Collecting and Using Your Personal Information</h2>
          
          <h3 className="text-lg font-semibold text-slate-100">Types of Data Collected</h3>
          <h4 className="text-base font-medium text-slate-200">Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include: First name and last name, Email address.
          </p>

          <h4 className="text-base font-medium text-slate-200">Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service, including Device IP address, browser type, pages visited, time spent, and diagnostic data.
          </p>

          <h3 className="text-lg font-semibold text-slate-100">Use of Your Personal Data</h3>
          <ul className="list-disc pl-6 space-y-2 text-slate-300">
            <li><strong>To provide and maintain Our Service</strong>, including to monitor usage.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> development and compliance of services purchased.</li>
            <li><strong>To contact You:</strong> via email, telephone, or electronic communications regarding security or updates.</li>
            <li><strong>To manage Your requests:</strong> to attend and manage Your requests to Us.</li>
          </ul>

          <h3 className="text-lg font-semibold text-slate-100">Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy (up to 24 months for account info and analytics logs).
          </p>

          <h3 className="text-lg font-semibold text-slate-100">Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update or delete Your information from within account settings or by contacting Us.
          </p>

          <h2 className="text-xl font-bold text-white pt-4 border-t border-slate-800">Children&apos;s and Minors&apos; Privacy</h2>
          <p>
            The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16.
          </p>

          <h2 className="text-xl font-bold text-white pt-4 border-t border-slate-800">Contact Us</h2>
          <p>If You have any questions about this Privacy Policy, You can contact Us:</p>
          <ul className="list-disc pl-6 space-y-1 text-slate-300">
            <li>By email: <a href="mailto:phanthaibaongoc11@gmail.com" className="text-indigo-400 hover:underline">phanthaibaongoc11@gmail.com</a></li>
          </ul>
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-slate-500 pt-4">
          © {new Date().getFullYear()} MayDo Fashion. All rights reserved. | <Link href="/login" className="text-slate-400 hover:text-slate-200">Đăng Nhập</Link>
        </div>
      </div>
    </div>
  );
}
